// These field numbers are the oneof arms in envelope.proto.
export const ENVELOPE_FIELD = Object.freeze({
  schemaVersion: 1,
  controlFrame: 2,
  authorityEvent: 3,
  telemetrySample: 4,
  hostCapabilities: 5,
  clientHello: 6,
  serverWelcome: 7,
  leaseRequest: 8,
  leaseResponse: 9,
  ping: 10,
  pong: 11,
  frameRejected: 12,
  leaseRelease: 13,
  leaseReleased: 14,
  linkLossCleared: 15,
  profileActivation: 16,
  controlActionResult: 17,
  controlActionCommand: 18,
  mediaAttachRequest: 19,
  videoDeliveryState: 20,
  scopeTransferOffer: 22,
});
